export { ShareCertificate } from './templates/share-certificate';
export type { ShareCertificateProps } from './templates/share-certificate';
export { DividendStatement } from './templates/dividend-statement';
export type { DividendStatementProps } from './templates/dividend-statement';
export { AnnualOverviewReport } from './templates/annual-overview-report';
export type { AnnualOverviewReportProps } from './templates/annual-overview-report';
export { ShareholderRegisterReport } from './templates/shareholder-register-report';
export type { ShareholderRegisterReportProps } from './templates/shareholder-register-report';
export { CapitalStatementReport } from './templates/capital-statement-report';
export type { CapitalStatementReportProps } from './templates/capital-statement-report';
export { ProjectInvestmentReport } from './templates/project-investment-report';
export type { ProjectInvestmentReportProps } from './templates/project-investment-report';
export { GiftCertificate } from './templates/gift-certificate';
export type { GiftCertificateProps } from './templates/gift-certificate';
export { ConvocationPdf, type ConvocationProps } from './templates/convocation';
export { VolmachtFormPdf, type VolmachtFormProps } from './templates/volmacht-form';
